default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_39380_development

test:
  <<: *default
  database: protospace_39380_test

production:
  <<: *default
  database: protospace_39380_production
  username: protospace_39380
  password: <%= ENV['PROTOSPACE_39380_DATABASE_PASSWORD'] %>
